version: '2.0'


services:

  em-client:
     container_name: em-client
     expose:
       - 3000
     ports:
       - 3000:3000
     build:
       context: .
       dockerfile: emClient/DockerFile
       args:
         - http_proxy
         - https_proxy
         - no_proxy
     volumes:
         - '.:/project/EM-app'
         
     links: 
        - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'

  emprocessor:
    container_name: emprocessor
    build:
      context: .
      dockerfile: emProcessor/DockerFile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
        - validator
    volumes:
        - '.:/project/EM-app'
 
  sawtooth-rest-api:
    container_name: rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004
  identity-tp:
    image: hyperledger/sawtooth-identity-tp:1.0
    container_name: sawtooth-identity-tp-default
    depends_on:
      - validator
    entrypoint: identity-tp -vv -C tcp://validator:4004
  validator:
    container_name: validator
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key && sawtooth keygen registration
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
  
